// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cw8.Models;

#nullable disable

namespace cw8.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20230124102300_new1")]
    partial class new1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cw8.Models.Student", b =>
                {
                    b.Property<int>("IdStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStudent"));

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NrIndeksu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RokStudiow")
                        .HasColumnType("int");

                    b.HasKey("IdStudent");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            IdStudent = 1,
                            Imie = "Jan",
                            Nazwisko = "Burak",
                            NrIndeksu = "1234",
                            RokStudiow = 1
                        },
                        new
                        {
                            IdStudent = 2,
                            Imie = "Karol",
                            Nazwisko = "Rzepa",
                            NrIndeksu = "55555",
                            RokStudiow = 2
                        });
                });

            modelBuilder.Entity("cw8.Models.Studia", b =>
                {
                    b.Property<int>("IdStudia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStudia"));

                    b.Property<int>("IdStudent")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tryb")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdStudia");

                    b.HasIndex("IdStudent");

                    b.ToTable("Studia");

                    b.HasData(
                        new
                        {
                            IdStudia = 1,
                            IdStudent = 1,
                            Nazwa = "Dlugie studia",
                            Tryb = "stacjonarne"
                        });
                });

            modelBuilder.Entity("cw8.Models.Studia", b =>
                {
                    b.HasOne("cw8.Models.Student", "Student")
                        .WithMany("IdStudiaNavigation")
                        .HasForeignKey("IdStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("cw8.Models.Student", b =>
                {
                    b.Navigation("IdStudiaNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
